//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodexo.DAL.SisVac.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public Aplicacion()
        {
            this.Rol = new HashSet<Rol>();
        }
    
        public long id_aplicacion { get; set; }
        public string nombre_sistema { get; set; }
        public string nombre_corto { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_reg { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
