//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodexo.DAL.SisVac.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excepcion
    {
        public Excepcion()
        {
            this.Excepcion_det = new HashSet<Excepcion_det>();
        }
    
        public long id_excepcion { get; set; }
        public string anio { get; set; }
        public Nullable<int> usu_reg { get; set; }
        public Nullable<int> usu_upd { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public Nullable<System.DateTime> fecha_upd { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<Excepcion_det> Excepcion_det { get; set; }
    }
}
