//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodexo.DAL.SisVac.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public long id_parametro { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<long> id_padre { get; set; }
    }
}
