//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodexo.DAL.SisVac.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public long id_perfil { get; set; }
        public string nombre_perfil { get; set; }
        public string codigo_perfil { get; set; }
        public Nullable<int> estado { get; set; }
        public string pagina { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public Nullable<int> usuario_reg { get; set; }
        public Nullable<long> id_rol { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
