//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodexo.DAL.SisVac.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Perfil = new HashSet<Perfil>();
            this.Usuario_Rol = new HashSet<Usuario_Rol>();
        }
    
        public long id_rol { get; set; }
        public string nombre_rol { get; set; }
        public string nombre_corto { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<long> id_aplicacion { get; set; }
    
        public virtual Aplicacion Aplicacion { get; set; }
        public virtual ICollection<Perfil> Perfil { get; set; }
        public virtual ICollection<Usuario_Rol> Usuario_Rol { get; set; }
    }
}
