//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodexo.DAL.SisVac.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SodexoEntities : DbContext
    {
        public SodexoEntities()
            : base("name=SodexoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aplicacion> Aplicacion { get; set; }
        public DbSet<Excepcion> Excepcion { get; set; }
        public DbSet<Excepcion_det> Excepcion_det { get; set; }
        public DbSet<Parametros> Parametros { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Usuario_Rol> Usuario_Rol { get; set; }
    }
}
