//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sodexo.DAL.SisVac.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Rol
    {
        public Nullable<long> id_usuario { get; set; }
        public Nullable<long> id_rol { get; set; }
        public long id_relacion { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
